branches:
  - main
  - "+([0-9])?(.{+([0-9]),x}).x"   # maintenance branches: 1.x, 2.x, etc.

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/github"
